intro to tensor

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
#creating tensor first with tf.constant()

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of tensor (ndim )
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# create a metrix
metrix = tf.constant([[10, 7], [7,10]])
metrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
metrix.ndim

2

In [ ]:
#create a anothe mertix
creat_metric = tf.constant([[10.,7], [3.,7],[8,.9]], dtype= tf.float16)
creat_metric

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  7. ],
       [ 3. ,  7. ],
       [ 8. ,  0.9]], dtype=float16)>

In [ ]:
creat_metric.ndim

2

In [ ]:
# lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      
                       [[7,8,9],
                      [10,11,12]]
                      ,
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# a scalar is a single number -- 0 dim
# a vector is number with direction (wind speed, and direction) -- 1 dim 
# matrix is 2nd dime array of numbers -- 2 dim
# a tensor is n-dim array of numbers(where n can be any number ) -- any dim

creating tensor with tf.variable

In [ ]:
# create the same tensor with tf.variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor 

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# lets try change one of the tensor in changeable tensor
changeable_tensor[0] = 7 

TypeError: ignored

In [ ]:
# try about .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# try about .assign()
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

creating random tensor

random tensors are of some abitrary size which contain random numbers

In [ ]:
# create two random tensor

In [ ]:
radom_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
radom_1 = radom_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

radom_1, random_2, radom_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
## shuffle the elemt in a tensor(valueable for when u want to shuffle your data so the inherent doesnt effect the learning)
not_shuffle = tf.constant([[10,7],
                           [10,3],
                           [2,5]])
not_shuffle.ndim
# shuffle our non shuffle tensor
tf.random.shuffle(not_shuffle)



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  3],
       [10,  7]], dtype=int32)>

In [ ]:
# if we want our shuffle tensor to be in the same order , we got to use global level random seed as well as operation level random seed

tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffle, seed= 42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  3],
       [ 2,  5]], dtype=int32)>

In [ ]:
## other ways to make tensor
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#create a tensor of all zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# you can also turn numpy arrays into tensors

### Turns numpy arrays as tensor

the main diff between numpy and tensor is that tensor can b run on gpu much faster

In [ ]:
import numpy as np
numpy_a = np.arange(1,25, dtype=np.int32) # create a numpy array between 1 and 25 
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_a, shape = (2,3,4
                                ))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

##Getting information from tensor
#### shape = the length of each of dimen, 
#### rank = the number of tensor dim, 
#### axis = a particular dim, 
#### size = the total number of itmes in tensor.

In [ ]:
# create rank 4 tensor
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

# Tensor can be indexing like python list

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
#rank 2 tensor

rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim, tf.size(rank_2_tensor)
rank_2_tensor

In [ ]:
# get the last elements of each row
rank_2_tensor[:, -1]

In [ ]:
rank_2_tensor[1:2, -1]

In [ ]:
# add extra dim to rank 2 dim
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
# alternate to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # -1 means expand the final axis or at the end of the dim

In [ ]:
tf.expand_dims(rank_2_tensor, axis = 0) # 0 means expand the 0[index] axis.

### Manipulating tensor (Tensor operations) bold text

In [ ]:
# Basic operation add value to a tensor using additional operator

In [ ]:
tensor1 = tf.constant([[10,7], [31,41]])  # original tensor is unchanged
tensor1+10

In [ ]:
tensor1

In [ ]:
# we can use tensorflow built - in function, tf.multiply(), tf.math.add()
tf.multiply(tensor1 , 10)

### Metrix Multiplication (Imp)

In [ ]:
# we can multiply metrix to another metrix by doing dot product.
# 1st row multiply by 1st column of another metrix
# dot product is when multiply matching members, then sum up
# metrix to single number is elementry 

##### there are two rules of tensor(or metrix) if we want to do metrix multiplication
1. the inner dimension much match
2. The resulting metrix has the shape of outer dimensions

In [ ]:
print(tensor1)

In [ ]:
tf.matmul(tensor1, tensor1)

In [ ]:
# we can do metriix multiplication in python by using "@" symbol
tensor1 @ tensor1

In [ ]:
# create a tensor (3,2)
x = tf.constant([[1,2], [3,4],[5,6]])

y = tf.constant([[7,8],[9,10],[11,12]])

x, y

In [ ]:
# try to multiply tensor of same shape, it can multiply and throw an error
tf.matmul(x, y)

In [ ]:
# lets try to change the shape of y tensor(metrix)
tf.reshape(y, shape=(2,3))

In [ ]:
# try to multiply x by reshaped y
tf.matmul(x, tf.reshape(y, shape=(2,3)))

In [ ]:
# try to reshape x instead of y
tf.matmul(tf.reshape(x, shape=(2,3)), y)

In [ ]:
# can we do the same with transpose
x, tf.transpose(x), tf.reshape(x, shape=(2,3))

1. transpose flip the axis
2. where reshape shuffle the tensor in to the shape we want

In [ ]:
# try metrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(x), y)

### Dot Product
 metrix multiplication is also referred to as the dot product.

 you can perform matrix multiplication using 
 tf.matmul()
 tf.tensordot()

In [ ]:
# perform a dot product on x and y (required x or y to be transposed) 
tf.tensordot(tf.transpose(x), y, axes = 1)

In [ ]:
# perform metric multiplication between x and y (transpose)

tf.matmul(x, tf.transpose(y))

In [ ]:
# perform metrix mult between x and y (reshape)
tf.matmul(x, tf.reshape(y, shape=(2,3)))

In [ ]:
# check the value of y and reshape and transpose y
print("normal y", y)
print("\n" )

print("y reshape", tf.reshape(y, shape=(2,3)), "\n")
print("y transpose", tf.transpose(y))

### generally when performing metrix mult on two tensor one of the axes doesnt line up, you will transpose rather than reshape one of the tensor , to satisfy metrix multiplication

## changing the data type of tensor

In [ ]:
# create a new tensor with default data type (float 32)
b = tf.constant([.7,.10])
b.dtype

In [ ]:
i = tf.constant([10,7])
i.dtype

In [ ]:
# change float32 to float16 (reduce precision)
b = tf.cast(b, dtype=tf.float16)
b.dtype

### Aggregation tensor
1. aggregation tensor = condensing them from multiple values down to smaller amount of value

In [ ]:

d = tf.constant([-7, -10])
d

In [ ]:
# get the absolute values = takes the all negative number of one tensor and turn them into positive numbers
tf.abs(d)

### form of aggregations
* min
* max
* mean of tensor
* sum

In [ ]:
e = tf.constant(np.random.randint(0,100, size = 50))
e

In [ ]:
tf.size(e), e.ndim, e.shape

In [ ]:
 #find the minimum
 tf.reduce_min(e)

In [ ]:
#find the maximum
tf.reduce_max(e)

In [ ]:
# find the mean
tf.reduce_mean(e)

In [ ]:
# sum of tensor
tf.reduce_sum(e)

In [ ]:
# to find variance of tensor
import tensorflow_probability as tfp # to find variance of tensor, we need access to tensorflow probability
tfp.stats.variance(e)

In [ ]:
# find std of tensor, to find std, we need to convert out tensor to float type
tf.math.reduce_std(tf.cast(e, dtype=tf.float32))

### Find the positional minimum and maximum

In [ ]:
# find the positional minimum and maximum ,create new tensor

tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

In [ ]:
# find the positional maximum
tf.argmax(f)

In [ ]:
# index of the largest value
f[tf.argmax(f)]

In [ ]:
tf.reduce_max(f)

In [ ]:
# find the poesitional minimum
tf.argmin(f)

In [ ]:
f[tf.argmin(f)]

# Squeezing a tensor (removing all single dimensions)

In [ ]:
# create a tensor  to get start
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
g

In [ ]:
g_squeeze =  tf.squeeze(g)
g_squeeze, g.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([1, 1, 1, 1, 50]))

## One-Hot-Encoding

In [ ]:
some_list = [1,2,1,4]

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#specify custom values for one hot - endcoder
tf.one_hot(some_list, depth=4, on_value='i like artificial intelligent', off_value='i didnt like to talk to girl')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'i didnt like to talk to girl',
        b'i like artificial intelligent',
        b'i didnt like to talk to girl', b'i didnt like to talk to girl'],
       [b'i didnt like to talk to girl', b'i didnt like to talk to girl',
        b'i like artificial intelligent',
        b'i didnt like to talk to girl'],
       [b'i didnt like to talk to girl',
        b'i like artificial intelligent',
        b'i didnt like to talk to girl', b'i didnt like to talk to girl'],
       [b'i didnt like to talk to girl', b'i didnt like to talk to girl',
        b'i didnt like to talk to girl', b'i didnt like to talk to girl']],
      dtype=object)>

# math function
* squaring
* log
* square root

In [ ]:
h = tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(h, dtype='float'))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(h, dtype='float'))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# tensorflow and numpy

## tensorflow beautifully interact with numpy arrays

In [ ]:
j = tf.constant(np.array([3., 7., 10.]))

In [ ]:
# convert tensor back to numpy
np.array(j)

array([ 3.,  7., 10.])

In [ ]:
# the default types of each are slightly different
numpy_j = tf.constant(np.array([3.,7.,10.]))

tesor_j = tf.constant([3., 7., 10. ])

numpy_j.dtype, tesor_j.dtype

(tf.float64, tf.float32)